// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXgf40tbWIQT0xswu5FCW7JpIoWx5lXbk',
    appId: '1:646905296299:web:ef46ede1da9c82867b4eee',
    messagingSenderId: '646905296299',
    projectId: 'to-do-list-bdj',
    authDomain: 'to-do-list-bdj.firebaseapp.com',
    storageBucket: 'to-do-list-bdj.appspot.com',
    measurementId: 'G-EZMKJEK085',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6tu1T09qjhkIOEOo7ctcJ_NbL1ZuOsdo',
    appId: '1:646905296299:android:d740e8414d50d9577b4eee',
    messagingSenderId: '646905296299',
    projectId: 'to-do-list-bdj',
    storageBucket: 'to-do-list-bdj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL2_H7YYR_HZ8TiPuLmLZ7F_z3fDSAFAc',
    appId: '1:646905296299:ios:e18674d0110454a67b4eee',
    messagingSenderId: '646905296299',
    projectId: 'to-do-list-bdj',
    storageBucket: 'to-do-list-bdj.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL2_H7YYR_HZ8TiPuLmLZ7F_z3fDSAFAc',
    appId: '1:646905296299:ios:79a736ccc79f03667b4eee',
    messagingSenderId: '646905296299',
    projectId: 'to-do-list-bdj',
    storageBucket: 'to-do-list-bdj.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
